hunav_loader:
  ros__parameters:
    agent0:
      behavior: 7
      cyclic_goals: false
      g1:
        h: 1.25
        x: 1.706169965075663
        y: 9.97377431906614
      goal_radius: 0.3
      goals:
      - g1
      group_id: -1
      id: 0
      init_pose:
        h: 0.0
        x: 4.519557625145515
        y: 9.91739299610894
        z: 1.25
      max_vel: 1.5
      radius: 0.4
      skin: 0
    agents:
    - agent0
    map: Warehouse_fixed
    publish_people: true
