hunav_loader:
  ros__parameters:
    agent0:
      behavior: 7
      cyclic_goals: false
      g1:
        h: 1.25
        x: 1.7228172293364317
        y: 4.128910505836473
      g2:
        h: 1.25
        x: 1.6728754365541265
        y: 7.0043579766536395
      goal_radius: 0.3
      goals:
      - g1
      - g2
      group_id: -1
      id: 0
      init_pose:
        h: 0.0
        x: 1.6895227008148943
        y: 0.9715564202333073
        z: 1.25
      max_vel: 1.5
      radius: 0.4
      skin: 0
    agents:
    - agent0
    map: Warehouse_fixed
    publish_people: true
