hunav_loader:
  ros__parameters:
    agent0:
      behavior: 7
      cyclic_goals: false
      g1:
        h: 1.25
        x: 1.8559953434225784
        y: -10.624202334630695
      g2:
        h: 1.25
        x: 1.7561117578579681
        y: -6.282840466926341
      g3:
        h: 1.25
        x: 4.785913853317808
        y: -6.094902723735679
      goal_radius: 0.3
      goals:
      - g1
      - g2
      - g3
      group_id: -1
      id: 0
      init_pose:
        h: 0.0
        x: 4.7692665890570405
        y: -10.455058365759097
        z: 1.25
      max_vel: 1.5
      radius: 0.4
      skin: 0
    agents:
    - agent0
    map: Warehouse_fixed
    publish_people: true
